
sudo: required

services:
    - docker

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -qy update

#install: 

script: 
    - make
    - docker build -t hello-docker .
    - docker images
    - docker run hello-docker





