
sudo: required

services:
    - docker

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -qy update

#install: 

script: 
    - make
    - docker build -t dustydust/hello-docker .
    - docker images
    - docker run dustydust/hello-docker
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push dustydust/hello-docker





