
sudo: required

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -qy update
    # wireshark.pc location: http://packages.ubuntu.com/tr/trusty/amd64/libwireshark-dev/filelist
    #somehow doesn't work: - export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}"

install: 
    - sudo apt-get -qy install pkg-config
    - sudo apt-get -qy install libwireshark-dev wireshark-dev
    - wget https://www.wireshark.org/download/src/wireshark-2.0.2.tar.bz2
    - tar xf wireshark-2.0.2.tar.bz2
    - mv wireshark-2.0.2 wireshark
    - cp -R ./plugins/doip ./wireshark/plugins/doip/ 
    - cp -R ./plugins/Custom.make ./wireshark/plugins/
    - cd ./wireshark && bash ./autogen.sh && cd ~-
    - cd ./wireshark/plugins && cat Makefile.am | sed 's/gryphon/doip\ gryphon/' > Makefile.am && cd ~-
    - cd ./wireshark && ./configure --enable-wireshark=no && cd ~-

script: 
    - pwd
    - ls ./wireshark/plugins/
    - ls ./wireshark/plugins/doip
    - make -C ./wireshark/plugins/doip





