
sudo: required

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -qy update

install: 
    - sudo apt-get -qy install wireshark-dev
    - sudo apt-get -qy install libwireshark-dev

script: make









